articulate/docker-node

6.0/Dockerfile
6.2/Dockerfile
6.2/imagemagick-policy.xml

Hey All - Very similar to @flintinatux comments the other day in the #tooling channel, we want to run on node 6 without babel.  
To achieve this, we need to bump our Node Docker image version.  
The question is, (and after lurking in the discussion in the #tooling channel) do we just go to 6.2 or 6.3? or do we even care and just do 6.x?
Would like to start a discussion about it, since in my non-docker-expert opinion if you do 6.x (aka Node:6) you'll always get the latest when you do a build...but point releases could have some big consequences.  Curious to hash this out! Thanks
cc: @tecnobrat @flintinatux @evilsoft @pklingem @fromonesrc

bump node:6 to node:6.2

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile

I tinkered with installing via apt, but it was a pain trying to import the gpg key.  The base node images install `npm` anyway, so there's no harm in installing via `npm` in my opinion.

install yarn via npm

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile

we should consider installing yarn from the apt repo as the yarn maintainers suggest.  It feels wrong to install via npm anyway.  The only downside is that we can't lock the version down if we want to.  @articulate/ops what are your thoughts?

install yarn from apt repo

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile

this version of yarn includes the `yarn import` command which will import the versions of node modules specified in `npm-shrinkwrap.json` into `yarn.lock` so no versions of packages will be changed when switching from shrinkwrap to yarn.  see: https://github.com/yarnpkg/yarn/pull/2580

bump yarn to 0.23.1

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile
Makefile

Allows us to limit our permissions to the app. To use, the app will need to set `USER` and `RUN chown` on the service dir. Example:
```
FROM articulate/articulate-node:6
COPY package.json yarn.lock $SERVICE_ROOT/
RUN yarn install --pure-lockfile
COPY . $SERVICE_ROOT/
RUN chown -R $SERVICE_USER /$SERVICE_ROOT
USER $SERVICE_USER
EXPOSE 3000
CMD yarn run rest
```

Service user and homedir

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile

the official docker node repo recently added yarn, it overrode the version of yarn we installed via the yarn apt repo, this is noted in #15.  Yarn 0.23.2 [breaks the integrity check on linux](https://github.com/yarnpkg/yarn/issues/3167).  This PR locks our version to 0.22.0 in the [same manner that the official docker node image does it](https://github.com/nodejs/docker-node/blob/master/7.9/Dockerfile#L34-L49) as suggested in [the PR that added yarn to the image](https://github.com/nodejs/docker-node/pull/337#issuecomment-282196215).
**To test**
*  `cd 7`
*  `docker build .`
>  Successfully built `4436d34d57c9`
*  `docker run --rm 4436d34d57c9 yarn --version`
> 0.22.0

lock yarn to 0.22.0

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile

Want to use new-relic native metrics stuff?  You will need `node-gyp` installed globally, otherwise it pukes. 
So this adds it to our default installs! 
🚢

Add in node-gyp global

---

4.4/Dockerfile
5.11/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile
8/Dockerfile

This update fixes an issue we ran into with Botzo, where dependencies were not being installed properly with the needed symlinks to run them.  @cdwills @dbertram do you see any issues with updating yarn here?

Update yarn in node:7

---

4.4/Dockerfile
5.11/Dockerfile
6.0/Dockerfile
6.2/Dockerfile
6/Dockerfile
7/Dockerfile
8/Dockerfile

yarn 1.0.1 is causing some problems with private npm module installs due to https://github.com/yarnpkg/yarn/issues/4335 - let's roll it back for now

Revert "bump yarn to 1.0.1"

---

5.11-jessie/Dockerfile
5.11/Dockerfile
6-jessie/Dockerfile
6.0-jessie/Dockerfile
6.0/Dockerfile
6.2-jessie/Dockerfile
6.2/Dockerfile
6/Dockerfile
7-jessie/Dockerfile
7/Dockerfile
8-jessie/Dockerfile
8/Dockerfile

This creates images for `[version_number]-jessie` and moves all of the `[version_number]` tagged image to inherit on the stretch images instead.

Swap to stretch as default, setup jessie as backup

---

4/Dockerfile
6/Dockerfile
8/Dockerfile
Makefile
README.md

Description:
- bump our version of `yarn` from `1.3.2` to `1.5.1`
- take advantage of bug and compatibility fixes/improvements
- change makefile so build path is `local/{image name}` (imo makes testing locally much easier)
Test:
- build locally
- tie a local repo to the new image and make sure all packages install (especially private and scoped)

Bump yarn version to 1.5.1

---

4/Dockerfile
6-alpine/Dockerfile
6/Dockerfile
8-alpine/Dockerfile
8/Dockerfile
Makefile

- we like yarn, we like updated and consistent yarn best.
- bump yarn to 1.6.0, and lock it there.
- add this to our new alpine images.

Bump yarn 1.6.0

---

6-alpine/Dockerfile
8-alpine/Dockerfile

- Our alpine images were not building native modules.
- This fixes that up, and will take care of any that have already been shipped.
cc: @pimpolderman

Add g++ to alpine images for native module building

---

6-alpine/Dockerfile
6/Dockerfile
8-alpine/Dockerfile
8/Dockerfile

Removing `npm` from all our node `6` and `8` docker images since we're using `yarn` pretty much across the board on everything now; this is to address some vulnerabilities being picked up on the `npm` module via twistlock and also clean things up.
Also removing the yarn installation from our Dockerfiles since the upstream `node` image that we're using is already installing yarn `1.6.0` for us - [example from node:8-alpine](https://github.com/nodejs/docker-node/blob/master/8/alpine/Dockerfile#L49-L67)
Example vuln report on `npm` from Twistlock:

Remove npm and yarn install

---

6-alpine/Dockerfile
6/Dockerfile

seeing this error when trying to install npm 6.1.0 on the node 6 images via `npm install npm -g`:
```
module.js:478
throw err;
^
Error: Cannot find module 'isarray'
at Function.Module._resolveFilename (module.js:476:15)
at Function.Module._load (module.js:424:25)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:32:15)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
script returned exit code 1
```
Better to uninstall `npm` completely then install it via the `install.sh` script provided by `npm` to control …

better way to install npm globally to node 6

---

10-alpine/Dockerfile
Makefile

Description
========
node 10 is going LTS in October and I would like to start using it as the base for some upcoming PoC work and new projects.  This just gets the image created and usable locally.
* I believe this will also get us bumped to latest yarn versions on all images since this will trigger base image rebuilds. so bonus.

Add `node:10-alpine` image

---

8-lambda/Dockerfile
8-lambda/entrypoint-lambda.sh
Makefile

I want this for dev'ing and deploying lambda stuffs.  Uses the legit `amazonlinux` image and links the `aws-sdk` used in the real lambda environment (can [check my work here](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)).  Also pulls in our Consul magic, so we can env like we always do.

Node 8 lambda

---

8-stretch-slim/Dockerfile

This adds several packages we need downstream:
- imagemagick
- make
- gcc
- g++
- binutils
(Items like 'make' can't be added on their own, it seems, it needs to be added as 'build-essential')
We add them here, as opposed to in the downstream images, because:
- otherwise their build times would be higher, and we want happy colleagues
- this way we can manage their versions right here, instead of in several places

Adding build essential and imagemagick to 8-stretch-slim

---

8-stretch-slim/Dockerfile
8-stretch-slim/imagemagick-policy.xml

One big reason why we install Imagemagick in the base image, is so that we can include a very strict policy file for it by default. 
This PR adds that policy file.

Add default security policy to Imagemagick

---

8-stretch-slim/Dockerfile

I thought that there would be more changes to come, but it seems we're good so far. 
This is now basically just a note saying that we use SERVICE_USER and SERVICE_ROOT in downstream Docker images too, which I didn't realise before.

Adding a debian-stretch-slim image

---

10-stretch-slim/imagemagick-policy.xml
8-stretch-slim/imagemagick-policy.xml

We've discovered the hard way today that specifying whitelisted image formats in one line doesn't work with the version of Imagemagick that Debian Stretch gives us at this time.
This PR changes the policy to actually work, and adds notes on what we learned today.

Editing imagemagick policy to work with our version

---

10-stretch-slim/imagemagick-policy.xml
8-stretch-slim/imagemagick-policy.xml

It turns out that a comment I added in our Imagemagick security policy, to explain a thing we fixed previously, made the whole policy void 🤦‍♂️ 
This PR removes that part of the comment from the node 8 and 10 images.

Remove policy-breaking comment

---

10-stretch-slim/Dockerfile
8-stretch-slim/Dockerfile

This PR removes the default node-gyp installed by npm. It comes with node-gyp 3.8.0 at this time, which pulls in a vulnerable tar version (2.2.1): https://www.npmjs.com/advisories/803.
We explicitly install a more recent node-gyp afterwards, so we can remove the vulnerable version.

Explicitly remove older node-gyp version to fix security issue

---

10-stretch-slim/Dockerfile
8-stretch-slim/Dockerfile

seeing some errors on builds for node projects today related to the PR that was merged recently to remove older `node-gyp` module; going to revert it for now to get those builds working again - we can revisit this later.

Revert "Explicitly remove older node-gyp version to fix security issue"

---

10-alpine/Dockerfile
10-stretch-slim/Dockerfile
6-alpine/Dockerfile
8-alpine/Dockerfile
8-stretch-slim/Dockerfile

In certain images, `node-gyp` has stopped working because upstream docker images have dropped python 2. `node-gyp` does not yet support python 2, so all native modules will fail to build.
This adds python 2 to all stretch-slim & alpine images. The stretch & lambda did not need changed.
**To Test**
1. Build all the things.
1. `docker run --rm -it local/articulate-node:TAG yarn add hot-shots` for all the things
1. Ensure yarn has no build errors

Add python 2 to images

---

10-alpine/Dockerfile
10-stretch-slim/Dockerfile
6-alpine/Dockerfile
8-alpine/Dockerfile
8-stretch-slim/Dockerfile

`node-gyp` 6 supports python 3. This removes python 2 from the builds by reverting https://github.com/articulate/docker-articulate-node/pull/54 as promised. I tested each image, & it seems no additional action is needed to get `node-gyp` to work.
Note, the default python version for stretch (not stretch-slim) is still python 2. Builds may still display EOL warnings but will continue to work.

Remove Python 2

---

10-lambda/Dockerfile
10-lambda/entrypoint-lambda.sh
Makefile

With Node 8's EOL only a few months away, create a new base image for Lambda's Node 10 runtime.

Add node 10 lambda image

---

.github/workflows/build.yml
12-buster-slim/Dockerfile
12-buster-slim/imagemagick-policy.xml
14-buster-slim/Dockerfile
14-buster-slim/imagemagick-policy.xml
Makefile

Adds `articulate/articulate-node:12-buster-slim` image.
This PR adds the ☝️ image so rise-api can update the `argon2` NPM package. Currently `argon2` is used within the customer API and will not work on stretch images. 
```bash
docker run -it node:12-stretch-slim bash
root@40ad307daa8a:/# npm install argon2
root@40ad307daa8a:/# node
Welcome to Node.js v12.22.6.
Type ".help" for more information.
> require('argon2')
Uncaught:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /node_modules/argon2/lib/binding/napi-v3/argon2.node)
```
buster is newer then stretch https://wiki.debian.org/LTS

Adding node-12-buster-slim image

---

12-lambda/Dockerfile
14-lambda/Dockerfile

Installing npm at the same time as yarn causes issues due to not being able to find npm. Move this to a different step.

fix(lambda): upgrade npm before installing any packages

---

.github/workflows/build.yml
.github/workflows/lint.yml
16-bullseye-slim/Dockerfile
16-bullseye-slim/imagemagick-policy.xml
Makefile

Bullseye-slim is needed for our https://github.com/articulate/docker-articulate-node-images repo which in turn is needed for https://github.com/articulate/images.
The root issue is M1 macs require glibc 2.29+ in order to run images locally (due to dependency on sharp)
Related issue `https://github.com/articulate/rise-authoring/issues/1168`
If you're adding a new image, make sure you have done the following.

Add 16-bullseye-slim image

---

16-bullseye-slim/Dockerfile
18-bullseye-slim/Dockerfile

This adds the [`retry`](https://github.com/minfrin/retry/tree/main) CLI tool to the images that have the package so that dependent images can do things like this:
```Dockerfile
RUN retry --times 4 -- yarn install --frozen-lockfile && yarn cache clean
```
It looks like the package is only available on `bullseye` for us: https://packages.debian.org/search?keywords=retry
If we were use our own script, we would have to copy and paste it in every folder, which isn't the end of the world. If we were to `ADD` a script from a URL, we would need to change the USER to root to chmod it to an executable.
This was borne out of https://github.com/articulate/docker-articulate-node/pull/86.
1. Check out this branch
2. Run `make`
3. Go to your local copy of https://github.com/articulate/rise-frontend/
4. …

feat: add retry CLI tool

---

.github/workflows/build.yml

This updates the `build.yml` file to run on PRs and pushes to them while also attempting to only publish when we are in the context of the `main` branch.
Borne out of https://github.com/articulate/docker-articulate-node/pull/86
If you're adding a new image, make sure you have done the following.

ci(build): run on PRs

---

.github/workflows/build.yml
.github/workflows/lint.yml
18-lambda/Dockerfile
Makefile
README.md

Lambda now supports Node 18.
Remove yarn since there are different ways to install depending on the version. If the project is using yarn, install the version they need.
Remove the aws-sdk npm package. v3 created different packages for each service. The runtime should also provide the sdk, so we don't need that installed.
Remove the service user. This image should used for building Lambda packages, so we don't care what user the container is using.
Remove the service directory. If we want to test the Lambda locally, it assumes it's ran in /var/tasks. Our pipeline doesn't care where the working directory is.
Cleanup README. Call out the recommended images.
If you're adding a new image, make sure you have done the following.

feat: add 18-lambda image

---

16-bullseye-slim/Dockerfile
16-buster-slim/Dockerfile
16-lambda/Dockerfile
16-stretch-slim/Dockerfile
18-bullseye-slim/Dockerfile
18-lambda/Dockerfile

Add an /opt/secrets script to help load Docker secrets so we can more easily use secrets.
The gid/uid should default to 1001, but make it explicit since you have to mount secrets by uid.
Only including this on 16 and 18 images since Node 14 is EOL soon and we don't want to encourage using that version

feat: add docker-secrets script

---

16-bullseye-slim/Dockerfile
16-buster-slim/Dockerfile
16-lambda/Dockerfile
16-stretch-slim/Dockerfile
18-bullseye-slim/Dockerfile
18-lambda/Dockerfile
Makefile
README.md

The `/opt/secrets` script hasn't been adopted yet, so move it to PATH to make it easier to use.
Improve local testing by building to the upstream name, then you don't have to modify Dockerfile to test

refactor: move secrets to PATH

---

14-buster-slim/Dockerfile
16-bullseye-slim/Dockerfile
16-buster-slim/Dockerfile
18-bullseye-slim/Dockerfile

Child images that attempt to install `node-gyp` are encountering errors and are failing to build.
```
#8 25.00 success Installed "node-gyp@9.4.0" with binaries:
#8 25.00       - node-gyp
#8 ERROR: process "/bin/sh -c yarn install --frozen-lockfile && yarn cache clean" did not complete successfully: exit code: 1
------
> [4/6] RUN yarn install --frozen-lockfile && yarn cache clean:
#8 23.43 warning Error running install script for optional dependency: "/service/node_modules/msgpackr-extract: Cannot read properties of undefined (reading 'config')"
#8 23.45 error An unexpected error occurred: "/service/node_modules/@datadog/native-appsec: Cannot read properties of undefined (reading 'getOption')".
#8 23.45 info If you think this is a bug, please open a bug report with the information …
```

Globally add node-gyp

---

.github/workflows/build.yml

If a repository isn't active, scheduled workflows are turned off and you're not really notified. Add a call to DMS so we can be alerted if the workflow stops running

ci(build): add DMS check in

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/lint.yml
20/lambda/Dockerfile
README.md

Add pull request template to make sure all the new image things are done (mostly README, which I forgot about initially)

feat(20): add lambda image

---

18-bullseye-slim/Dockerfile
18/base/Dockerfile
20/base/Dockerfile

Use dumb-init to handle zombie processes and forwarding signals.
Not including in Lambda images as it's not as easy to install and our use-case for those images isn't long running processes, so we don't need the things dumb-init gives us

feat: add dumb-init as entrypoint

---

22/lambda/Dockerfile
README.md

**issue:** https://github.com/articulate/identity/issues/1511
Adding the `node:22-lambda` Docker image. While working on porting our services from Node 18 to Node 22, we noticed this lambda runtime still didn't have its own Docker image, so this PR adds it based on the existing Node 20 Lambda Dockerfile. 
If you're adding a new image, make sure you have done the following:

feat(lambda): add Node 22 image

---

.github/CODEOWNERS
18-bullseye-slim/Dockerfile
18/base/Dockerfile
18/lambda/Dockerfile
20/lambda/Dockerfile
22/lambda/Dockerfile

npm 11 requires Node 20
Other changes:
* The old style of ENV key value is deprecated and is now ENV key=value

fix(18-bullseye-slim): pin node to 10

---

22/lambda/Dockerfile

https://github.com/articulate/devex-sre/issues/1453
If you're adding a new image, make sure you have done the following:

feat(22): uses corepack package loader for lambda build
